### ISSUE TITLE
Error？

### ISSUE THREAD

**Issue by Gullinkambi07** [dougmill/StarTech_3.3_fixes#1]
Error in common\scripted_triggers\~str_scripted_triggers_buildings_ai.txt: Ln:
19 Col: 86 (UTF16-Col: 51)
                       str_num_free_districts_mining = { operator = = num = 0 }
                                                                    ^
Note: The column count assumes a tab stop distance of 8 chars.
Expecting: value

**Comment by dougmill** [comment]
I've seen this reported before. It's labeled an error by a third party tool, not by the actual game, and this line is part of the published StarTech mod and works correctly as is.
